sudo: false
language: node_js
node_js:
- '0.10'
before_script:
- npm install
script:
- node build.js
install:
- npm install -g firebase-tools
deploy:
  provider: script
  script: firebaseDeploy.sh
  on:
    branch: production
notifications:
  slack: saasquatch:RIZoBfbBnFIlgIoAW0C17ugr