sudo: false
language: node_js
node_js:
- '0.10'
- '0.11'
before_script:
- npm install
script:
- node build.js
install:
- npm install -g firebase-tools
deploy:
  provider: script
  script: firebaseDeploy.sh
  on:
  	branch: production
notifications:
  slack: saasquatch:RIZoBfbBnFIlgIoAW0C17ugr
env:
  global:
    secure: rFtuQZWxeWaIgOAA1NLBSYibtDMittSS+fNAvR17ISqRx0fq00PDeDj01GkfuwBbuXt+x68SWSYq1JEC2rBnETUWQWtLQbkF5vhT6bVq30+xAcu2Kb7KtHYujqYEKhtkeV2sArk2txQJF9sf+DBhqiY7tfTHeVxYSfLedDtAdPw=
