sudo: false
language: node_js
before_script:
- npm install
script:
- npm run production
deploy:
  skip_cleanup: true
  provider: script
  script: ./firebaseDeploy.sh
  on:
    branch: production
notifications:
  slack: saasquatch:RIZoBfbBnFIlgIoAW0C17ugr