-   title: Product Updates August 2017
    datePublished: "2017-08-16"
    tags:
        - feature-release
        - product-update
    content: |
        #### Custom Themes Gallery
        We’ve created a gallery displaying a selection of  custom themes created to date. Use these examples to help provide some inspiration for your own referral program, or get our custom theme team to help you build the best design that embodies your company's brand. See the gallery [here](https://docs.referralsaasquatch.com/themes/custom-theme-gallery/). 
        
        #### Additional values added to Rewards Reporting
        
        To simplify reward balance tracking we’ve added 2 new values to our reports. Now you can take daily snapshots of the reward balances SaaSquatch is holding onto, for better reward management.
        
        Add the following values to your Reward Balance report in the SaaSquatch portal to get better tracking results: 
        - Current Available Credit
        - totalAssignedCredit (*New*)
        - totalRedeemedCredit (*New*)
        
        #### Lookup a users share URL’s
        
        We’ve added a quick way to lookup a full list of all of a user's share links. This new API method returns the full list of referral share links for a user. Optional filter parameters are available to return only links of a specific share or engagement medium. See how in our developer documentation [here](https://docs.referralsaasquatch.com/api/methods/#lookup-a-users-share-urls). 
        
        #### Improved referral share tracking
        
        More information has been made available through additional UTM parameters, which provides a more granular insight into your participants referral activity. This has been implemented in the SaaSquatch system and requires no additional changes by the customer. Read more in our Success Centre Docs [here](https://docs.referralsaasquatch.com/success/share-options/). 
        
        #### Widget Referral Ordering
        
        We've updated the widget data to order referrals by date instead of what was previously a more random ordering. This provides participants with a more logical and engaging view of their referral progress. The ordering change has been implemented in the SaaSquatch system and requires no additional changes by the customer. To review the widgets and touch points used in a referral program, see our [success docs](https://docs.referralsaasquatch.com/success/touchpoints/).
        
        #### Simplify User Creation in Portal
        
        We've eased back the restrictions for creating new users in the portal, making the process simple and more efficient for all users. Now participants or program administrators can add new users by last name only. 
        
        #### User Blocking 
        
        To minimize fraud, a new security feature has been added that allows campaign managers to block specific users by IP Address or name. This feature can be enabled or disabled at anytime through the Security settings directly in the portal.

-   title: June 2017 Release Recap
    datePublished: "2017-07-05"
    tags:
        - monthly-update
    content: |
        It has been a busy kick off to the summer for SaaSquatch, and this past June turned out to be one of the busiest on record with a few highlights worth mentioning:
        
        We saw a record breaking number of new customer sign-ups
        SaaSquatch launched programs on 4 continents
        A new client program saw a user base increase of +20,000 in its first month (new PB!)
        Our newest reward customization feature, Fuel Tank, is now available on all plans
        
        ![yay](https://www.referralsaasquatch.com/wp-content/uploads/2017/07/Badge-1-150x150.png)
        
        As things continue to ramp up for SaaSquatch, we’ll be sure to keep you posted on what’s new in the monthly Release Recaps. Here’s our top feature updates and releases from this past month.
        
        #### Mobile – Universal SDK’s
        
        The SaaSquatch mobile SDKs, Android and iOS, have all been updated. With these updates you can now compile your app both for emulators and physical devices without changing your environment settings. Additionally they have been updated to support the newest SaaSquatch open APIs. Read more…
        
        #### Fraud Prevention – Global Reward Limit
        
        This new fraud prevention feature allows you to limit your liability without sacrificing the average end user’s experience. The new fraud filter places a limit on the maximum number of rewards the SaaSquatch system will give out in a single day.
        
        #### Program Experience – Broken Program Detection
        
        A new feature has been added to our system for all users that detects broken installations and alerts our success team so we can pre-emptively assist with installation issues.
        
        #### Portal – Enhanced Portal Pagination
        
        We understand that there are some real power portal users out there who have to manage a lot of data. To help these users out a bit, we’ve added a new pagination control that lets program administrators manage more records at a time.
        
        #### Referral Widget – User-Only Referral Data
        
        This feature improvement allows customers to enable personalized widgets that only show referrals specific to individual users and not the shared account referrals. This is particularly useful for any customer offering gift cards as a referral reward.
        
        #### Referral Widget – Self-identified Widgets
        
        The self-identify feature in the widget has been upgraded so that customers, both referring and referred, can provide their first and last name. Additionally, there are new options in the theme section to control which self-identify fields will appear in the widget.
        
        #### Program Experience – Short Link Fallback URL
        
        Customers who use custom short links may have noticed that when you visit their custom short link domain without referral details you get a blank page. Now all customers with custom short links can configure a URL where users get redirected to instead of the error.
        
        #### Infrastructure  – Automated Widget Regression Tests
        
        SaaSquatch is committed to the highest possible system uptime. In response to a short, temporary outage event last month, we have added automated mechanisms that will detect future widget outages to limit widget downtime and keep programs running smoothly.
        
        Stay tuned for more exciting releases and updates on our blog! Have questions or comments? We’d love to hear from you!
    